services:
  - type: web
    name: angular-signup-verification
    env: static
    nodeVersion: 16.20.0
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    staticPublishPath: dist/angular-signup-verification-boilerplate
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 