services:
  - type: web
    name: angular-signup-verification
    env: static
    nodeVersion: 18.17.0
    buildCommand: |
      npm install --legacy-peer-deps
      ng serve --configuration=production
    staticPublishPath: dist/angular-signup-verification-boilerplate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 