services:
  - type: web
    name: angular-signup-verification
    env: static
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: ./dist/angular-signup-verification-boilerplate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 