services:
  - type: web
    name: angular-signup-verification
    env: static
    nodeVersion: 18.17.0
    buildCommand: |
      npm install --legacy-peer-deps
      npm install -g @angular/cli
      npm run build
    staticPublishPath: dist/angular-signup-verification-boilerplate
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 