services:
  - type: web
    name: angular-signup-verification-boilerplate
    env: static
    buildCommand: npm run build
    staticPublishPath: dist/angular-signup-verification-boilerplate
    envVars:
      - key: NODE_VERSION
        value: 16.20.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 