services:
  - type: web
    name: angular-signup-verification
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: dist/angular-signup-verification-boilerplate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 